<?php

use Illuminate\Database\Seeder;

class DebtorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        for ($id = 1; $id <= 3; $id++)
            {
                DB::table('debtors')->insert([
                    'company' => 'COBOLD  SIA',
                    'created_by' => $id,
                    'reg_number' => '50003316671',
                    'debt' => '1000.00',
                    'legal_address' => 'Ganību dambis 19',
                    'city' => 'Rīga',
                    'country' => 'LV',
                    'postal_code' => 'LV-1005',
                    'phone' => '+371 67389055',
                    'fax' => '+371 67389055',
                    'email' => 'info@cobold.lv',
                    'homepage' => 'www.cobold.lv',
                    'bank_name' => 'AS Swedbank',
                    'bank_account_number' => 'LV80 BANK 0000 4351 9500 1',
                    'status' => 'hopeless',
                    'note' => 'Mežkopība un citas mežsaimniecības darbības',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' =>  date("Y-m-d H:i:s")]);

                DB::table('debtors')->insert([
                    'company' => 'Easy Bolt',
                    'created_by' => $id,
                    'reg_number' => '41203055977',
                    'debt' => '1400.00',
                    'legal_address' => 'Celtnieku iela 2 - 5',
                    'city' => 'Talsi',
                    'country' => 'LV',
                    'postal_code' => 'LV-3201',
                    'phone' => '+371 28640058',
                    'fax' => '+37128640058',
                    'email' => 'easybolt@hotmail.lv',
                    'homepage' => 'easybolt.lv',
                    'bank_name' => 'Luminor',
                    'bank_account_number' => 'LV89 5241 41203 055977',
                    'status' => 'insolvency',
                    'note' => 'Mazumtirdzniecības veidi ārpus veikaliem',
                    'created_at' => '2019-11-30 21:24:54',
                    'updated_at' => '2020-06-22 11:50:39']);

                DB::table('debtors')->insert([
                    'company' => 'SEANLI',
                    'created_by' => $id,
                    'reg_number' => '41502039480',
                    'debt' => '2300.00',
                    'legal_address' => 'Senlejas iela 78',
                    'city' => 'Daugavpils',
                    'country' => 'LV',
                    'postal_code' => ' LV-5414',
                    'phone' => '+371 27640051',
                    'fax' => '+371 27640051',
                    'email' => 'seanlishor@gmail.lv',
                    'homepage' => 'seanlishor.lv',
                    'bank_name' => 'Nordea',
                    'bank_account_number' => 'LV85 41502 039480 111',
                    'status' => 'debt_collected',
                    'note' => 'Saprātīga konstrukcija, darbība un apkope',
                    'created_at' => '2019-04-01 11:33:51',
                    'updated_at' => '2020-05-21 11:11:39']);

                DB::table('debtors')->insert([
                    'company' => 'Good fish',
                    'created_by' => $id,
                    'reg_number' => '40103611012',
                    'debt' => '1700.00',
                    'legal_address' => ' Gaujienas iela 3A - 10 ',
                    'city' => 'Riga',
                    'country' => 'LV',
                    'postal_code' => 'LV-1005',
                    'phone' => '+371 27333351',
                    'fax' => '+371 27333351',
                    'email' => 'goodfish@mail.lv',
                    'homepage' => 'goodfishas.lv',
                    'bank_name' => 'Swedbank',
                    'bank_account_number' => 'LV77 4155 401036 11012',
                    'status' => 'in_court',
                    'note' => 'Zivju ražošana',
                    'created_at' => '2017-07-08 10:33:41',
                    'updated_at' => '2020-02-05 22:10:29']);

                DB::table('debtors')->insert([
                    'company' => 'TRONS',
                    'created_by' => $id,
                    'reg_number' => '50002000581',
                    'debt' => '3400.00',
                    'legal_address' => ' Imantas 5. linija 18 ',
                    'city' => 'Riga',
                    'country' => 'LV',
                    'postal_code' => 'LV-1067',
                    'phone' => '+371 271337351',
                    'fax' => '+371 27133751',
                    'email' => 'tronsh@mail.lv',
                    'homepage' => 'tronasa.lv',
                    'bank_name' => 'Swedbank',
                    'bank_account_number' => 'LV85 8855 00020 00581 11',
                    'status' => 'in_court',
                    'note' => 'Suhova individualais komercuznemums ',
                    'created_at' => '2014-07-08 10:39:41',
                    'updated_at' => '2020-01-05 12:10:29']);

                DB::table('debtors')->insert([
                    'company' => 'ATT Parquet',
                    'created_by' => $id,
                    'reg_number' => '44103142279',
                    'debt' => '7400.00',
                    'legal_address' => ' Marsa gatve 6 - 24',
                    'city' => 'Riga',
                    'country' => 'LV',
                    'postal_code' => ' LV-1082 ',
                    'phone' => '+371 371337352',
                    'fax' => '+371 37133752',
                    'email' => 'parqwet@mail.lv',
                    'homepage' => 'praqwet.lv',
                    'bank_name' => 'Luminor',
                    'bank_account_number' => 'LV45 4103 1422 7944',
                    'status' => 'insolvency',
                    'note' => 'Sabiedriba ar ierobezotu atbildibu ',
                    'created_at' => '2017-02-08 12:32:11',
                    'updated_at' => '2020-06-05 10:10:19']);

                DB::table('debtors')->insert([
                    'company' => 'JJ-WORK',
                    'created_by' => $id,
                    'reg_number' => '42103106744',
                    'debt' => '700.00',
                    'legal_address' => 'Rucavas pag. "Dizpriedes"',
                    'city' => 'Rucavas nov.',
                    'country' => 'LV',
                    'postal_code' => ' LV-3477',
                    'phone' => '+374 374337352',
                    'fax' => '+374 37433752',
                    'email' => 'jj-work@mail.lv',
                    'homepage' => 'jj-work.lv',
                    'bank_name' => 'Luminor',
                    'bank_account_number' => 'LV84 4210 3451 1067 7744',
                    'status' => 'insolvency',
                    'note' => 'Sabiedriba ar ierobezotu atbildibu ',
                    'created_at' => '2016-02-08 12:30:11',
                    'updated_at' => '2020-04-05 10:11:19']);

                DB::table('debtors')->insert([
                    'company' => 'SIA KKK',
                    'created_by' => $id,
                    'reg_number' => '44103139989',
                    'debt' => '9900.00',
                    'legal_address' => 'Skukisi, "Rukisi"',
                    'city' => 'Garkalnes nov.',
                    'country' => 'LV',
                    'postal_code' => 'LV-2137',
                    'phone' => '+372 374637352',
                    'fax' => '+374 37463752',
                    'email' => 'siawork@mail.lv',
                    'homepage' => 'siakwork.lv',
                    'bank_name' => 'Swedbank',
                    'bank_account_number' => 'LV52 4410 3139 9897',
                    'status' => 'hopeless',
                    'note' => 'Sabiedriba ar ierobezotu atbildibu ',
                    'created_at' => '2014-02-11 16:30:11',
                    'updated_at' => '2020-02-07 10:11:39']);

                DB::table('debtors')->insert([
                    'company' => ' GOD HAND ',
                    'created_by' => $id,
                    'reg_number' => '43602026495',
                    'debt' => '5740.00',
                    'legal_address' => ' Edvarta Virzas iela 1',
                    'city' => 'Iecavas nov., Iecava ',
                    'country' => 'LV',
                    'postal_code' => 'LV-3913',
                    'phone' => '+371 36563752',
                    'fax' => '+371 36563752',
                    'email' => 'handgod@mail.lv',
                    'homepage' => 'hundod.lv',
                    'bank_name' => 'Swedbank',
                    'bank_account_number' => 'LV85 4360 2088 2649 7565',
                    'status' => 'hopeless',
                    'note' => '(IK) ',
                    'created_at' => '2018-06-16 08:30:11',
                    'updated_at' => '2020-01-05 01:11:39']);

                DB::table('debtors')->insert([
                    'company' => 'Easy Bolt',
                    'created_by' => $id,
                    'reg_number' => '41203055977',
                    'debt' => '1400.00',
                    'legal_address' => 'Celtnieku iela 2 - 5',
                    'city' => 'Talsi',
                    'country' => 'LV',
                    'postal_code' => ' LV-3201',
                    'phone' => '+371 28640058',
                    'fax' => '+37128640058',
                    'email' => 'easybolt@hotmail.lv',
                    'homepage' => 'easybolt.lv',
                    'bank_name' => 'Luminor',
                    'bank_account_number' => 'LV78 2145 4120 3452 0559',
                    'status' => 'insolvency',
                    'note' => 'Mazumtirdzniecības veidi ārpus veikaliem',
                    'created_at' => '2019-11-30 21:24:54',
                    'updated_at' => '2020-06-22 11:50:39']);

                DB::table('debtors')->insert([
                    'company' => 'SEANLI',
                    'created_by' => $id,
                    'reg_number' => '41502039480',
                    'debt' => '2300.00',
                    'legal_address' => 'Senlejas iela 78',
                    'city' => 'Daugavpils',
                    'country' => 'LV',
                    'postal_code' => 'LV-5414',
                    'phone' => '+371 27640051',
                    'fax' => '+371 27640051',
                    'email' => 'seanlishor@gmail.lv',
                    'homepage' => 'seanlishor.lv',
                    'bank_name' => 'Nordea',
                    'bank_account_number' => 'LV41 5027 0394 8075',
                    'status' => 'debt_collected',
                    'note' => 'Saprātīga konstrukcija, darbība un apkope',
                    'created_at' => '2019-04-01 11:33:51',
                    'updated_at' => '2020-05-21 11:11:39']);

                DB::table('debtors')->insert([
                    'company' => 'Good fish',
                    'created_by' => $id,
                    'reg_number' => '40103611012',
                    'debt' => '1700.00',
                    'legal_address' => ' Gaujienas iela 3A - 10 ',
                    'city' => 'Riga',
                    'country' => 'LV',
                    'postal_code' => 'LV-1005',
                    'phone' => '+371 27333351',
                    'fax' => '+371 27333351',
                    'email' => 'goodfish@mail.lv',
                    'homepage' => 'goodfishas.lv',
                    'bank_name' => 'Swedbank',
                    'bank_account_number' => 'LV47 4010 3678 1101 7852',
                    'status' => 'in_court',
                    'note' => 'Zivju ražošana',
                    'created_at' => '2017-07-08 10:33:41',
                    'updated_at' => '2020-02-05 22:10:29']);

                DB::table('debtors')->insert([
                    'company' => 'TRONS',
                    'created_by' => $id,
                    'reg_number' => '50002000581',
                    'debt' => '3400.00',
                    'legal_address' => ' Imantas 5. linija 18 ',
                    'city' => 'Riga',
                    'country' => 'LV',
                    'postal_code' => 'LV-1067',
                    'phone' => '+371 271337351',
                    'fax' => '+371 27133751',
                    'email' => 'tronsh@mail.lv',
                    'homepage' => 'tronasa.lv',
                    'bank_name' => 'Swedbank',
                    'bank_account_number' => 'LV84 5002 0582 0058 1236',
                    'status' => 'in_court',
                    'note' => 'Suhova individualais komercuznemums ',
                    'created_at' => '2014-07-08 10:39:41',
                    'updated_at' => '2020-01-05 12:10:29']);

                DB::table('debtors')->insert([
                    'company' => 'ATT Parquet',
                    'created_by' => $id,
                    'reg_number' => '44103142279',
                    'debt' => '7400.00',
                    'legal_address' => ' Marsa gatve 6 - 24',
                    'city' => 'Riga',
                    'country' => 'LV',
                    'postal_code' => 'LV-1082',
                    'phone' => '+371 371337352',
                    'fax' => '+371 37133752',
                    'email' => 'parqwet@mail.lv',
                    'homepage' => 'praqwet.lv',
                    'bank_name' => 'Luminor',
                    'bank_account_number' => 'LV41 03142 0279 4848 8541',
                    'status' => 'insolvency',
                    'note' => 'Sabiedriba ar ierobezotu atbildibu ',
                    'created_at' => '2017-02-08 12:32:11',
                    'updated_at' => '2020-06-05 10:10:19']);

                DB::table('debtors')->insert([
                    'company' => 'JJ-WORK',
                    'created_by' => $id,
                    'reg_number' => '42103106744',
                    'debt' => '700.00',
                    'legal_address' => 'Rucavas pag. "Dizpriedes"',
                    'city' => 'Rucavas nov.',
                    'country' => 'LV',
                    'postal_code' => 'LV-3477',
                    'phone' => '+374 374337352',
                    'fax' => '+374 37433752',
                    'email' => 'jj-work@mail.lv',
                    'homepage' => 'jj-work.lv',
                    'bank_name' => 'Luminor',
                    'bank_account_number' => 'LV42 1037 1067 4454',
                    'status' => 'insolvency',
                    'note' => 'Sabiedriba ar ierobezotu atbildibu ',
                    'created_at' => '2016-02-08 12:30:11',
                    'updated_at' => '2020-04-05 10:11:19']);

                DB::table('debtors')->insert([
                    'company' => 'SIA KKK',
                    'created_by' => $id,
                    'reg_number' => '44103139989',
                    'debt' => '9900.00',
                    'legal_address' => 'Skukisi, "Rukisi"',
                    'city' => 'Garkalnes nov.',
                    'country' => 'LV',
                    'postal_code' => 'LV-2137',
                    'phone' => '+372 374637352',
                    'fax' => '+374 37463752',
                    'email' => 'siawork@mail.lv',
                    'homepage' => 'siakwork.lv',
                    'bank_name' => 'Swedbank',
                    'bank_account_number' => 'LV74 4410 3178 3998 7879',
                    'status' => 'hopeless',
                    'note' => 'Sabiedriba ar ierobezotu atbildibu ',
                    'created_at' => '2014-02-11 16:30:11',
                    'updated_at' => '2020-02-07 10:11:39']);

                DB::table('debtors')->insert([
                    'company' => ' GOD HAND ',
                    'created_by' => $id,
                    'reg_number' => '43602026495',
                    'debt' => '5740.00',
                    'legal_address' => ' Edvarta Virzas iela 1',
                    'city' => 'Iecavas nov., Iecava ',
                    'country' => 'LV',
                    'postal_code' => 'LV-3913',
                    'phone' => '+371 36563752',
                    'fax' => '+371 36563752',
                    'email' => 'handgod@mail.lv',
                    'homepage' => 'hundod.lv',
                    'bank_name' => 'Swedbank',
                    'bank_account_number' => 'LV78 4348 7556 0207 2649',
                    'status' => 'hopeless',
                    'note' => '(IK) ',
                    'created_at' => '2018-06-16 08:30:11',
                    'updated_at' => '2020-01-05 01:11:39']);

                DB::table('debtors')->insert([
                    'company' => '"Mix L" ',
                    'created_by' => $id,
                    'reg_number' => '45403031751',
                    'debt' => '2920.77',
                    'legal_address' => ' Dzeguzu iela 7 - 20 ',
                    'city' => 'Riga',
                    'country' => 'LV',
                    'postal_code' => 'LV-1007',
                    'phone' => '+371 22563731',
                    'fax' => '+371 22563731',
                    'email' => 'mixl@mail.lv',
                    'homepage' => 'seamixl.lv',
                    'bank_name' => 'Luminor',
                    'bank_account_number' => ' LV57 5403 0385 1751 4897',
                    'status' => 'hopeless',
                    'note' => '(SIA) Kurzeme purvins ',
                    'created_at' => '2019-06-16 08:30:41',
                    'updated_at' => '2020-01-07 05:01:39']);

                DB::table('debtors')->insert([
                    'company' => '"Mix L" ',
                    'created_by' => $id,
                    'reg_number' => '45403031751',
                    'debt' => '2920.77',
                    'legal_address' => 'Dzeguzu iela 7 - 20',
                    'city' => 'Riga',
                    'country' => 'LV',
                    'postal_code' => 'LV-1007',
                    'phone' => '+371 22563731',
                    'fax' => '+371 22563731',
                    'email' => 'mixl@mail.lv',
                    'homepage' => 'seamixl.lv',
                    'bank_name' => 'Luminor',
                    'bank_account_number' => 'LV57 7845 4030 3758 1751',
                    'status' => 'hopeless',
                    'note' => '(SIA) Mix LV FM 102,7 ',
                    'created_at' => '2019-06-16 08:30:41',
                    'updated_at' => '2020-01-07 05:01:39']);

                DB::table('debtors')->insert([
                    'company' => 'Easy Bolt',
                    'created_by' => $id,
                    'reg_number' => '41203055977',
                    'debt' => '1400.00',
                    'legal_address' => 'Celtnieku iela 2 - 5',
                    'city' => 'Talsi',
                    'country' => 'LV',
                    'postal_code' => 'LV-3201',
                    'phone' => '+371 28640058',
                    'fax' => '+37128640058',
                    'email' => 'easybolt@hotmail.lv',
                    'homepage' => 'easybolt.lv',
                    'bank_name' => 'Luminor',
                    'bank_account_number' => 'LV21 7896 4120 3787 5597',
                    'status' => 'insolvency',
                    'note' => 'Mazumtirdzniecības veidi ārpus veikaliem',
                    'created_at' => '2019-11-30 21:24:54',
                    'updated_at' => '2020-06-22 11:50:39']);

                DB::table('debtors')->insert([
                    'company' => 'SEANLI',
                    'created_by' => $id,
                    'reg_number' => '41502039480',
                    'debt' => '2300.00',
                    'legal_address' => 'Senlejas iela 78',
                    'city' => 'Daugavpils',
                    'country' => 'LV',
                    'postal_code' => 'LV-5414',
                    'phone' => '+371 27640051',
                    'fax' => '+371 27640051',
                    'email' => 'seanlishor@gmail.lv',
                    'homepage' => 'seanlishor.lv',
                    'bank_name' => 'Nordea',
                    'bank_account_number' => 'LV41 5027 0394 8078 7854',
                    'status' => 'debt_collected',
                    'note' => 'Saprātīga konstrukcija, darbība un apkope',
                    'created_at' => '2019-04-01 11:33:51',
                    'updated_at' => '2020-05-21 11:11:39']);

                DB::table('debtors')->insert([
                    'company' => 'Good fish',
                    'created_by' => $id,
                    'reg_number' => '40103611012',
                    'debt' => '1700.00',
                    'legal_address' => 'Gaujienas iela 3A - 10',
                    'city' => 'Riga',
                    'country' => 'LV',
                    'postal_code' => 'LV-1005',
                    'phone' => '+371 27333351',
                    'fax' => '+371 27333351',
                    'email' => 'goodfish@mail.lv',
                    'homepage' => 'goodfishas.lv',
                    'bank_name' => 'Swedbank',
                    'bank_account_number' => 'LV74 4074 1036 1101 4582',
                    'status' => 'in_court',
                    'note' => 'Zivju ražošana',
                    'created_at' => '2017-07-08 10:33:41',
                    'updated_at' => '2020-02-05 22:10:29']);

                DB::table('debtors')->insert([
                    'company' => 'TRONS',
                    'created_by' => $id,
                    'reg_number' => '50002000581',
                    'debt' => '3400.00',
                    'legal_address' => 'Imantas 5. linija 18',
                    'city' => 'Riga',
                    'country' => 'LV',
                    'postal_code' => 'LV-1067',
                    'phone' => '+371 271337351',
                    'fax' => '+371 27133751',
                    'email' => 'tronsh@mail.lv',
                    'homepage' => 'tronasa.lv',
                    'bank_name' => 'Swedbank',
                    'bank_account_number' => 'LV50 0020 0058 1485 7857',
                    'status' => 'in_court',
                    'note' => 'Suhova individualais komercuznemums ',
                    'created_at' => '2014-07-08 10:39:41',
                    'updated_at' => '2020-01-05 12:10:29']);

                DB::table('debtors')->insert([
                    'company' => 'ATT Parquet',
                    'created_by' => $id,
                    'reg_number' => '44103142279',
                    'debt' => '7400.00',
                    'legal_address' => ' Marsa gatve 6 - 24',
                    'city' => 'Riga',
                    'country' => 'LV',
                    'postal_code' => ' LV-1082 ',
                    'phone' => '+371 371337352',
                    'fax' => '+371 37133752',
                    'email' => 'parqwet@mail.lv',
                    'homepage' => 'praqwet.lv',
                    'bank_name' => 'Luminor',
                    'bank_account_number' => 'LV32 4103 1422 2793 4321',
                    'status' => 'insolvency',
                    'note' => 'Sabiedriba ar ierobezotu atbildibu ',
                    'created_at' => '2017-02-08 12:32:11',
                    'updated_at' => '2020-06-05 10:10:19']);

                DB::table('debtors')->insert([
                    'company' => 'JJ-WORK',
                    'created_by' => $id,
                    'reg_number' => '42103106744',
                    'debt' => '700.00',
                    'legal_address' => 'Rucavas pag. "Dizpriedes"',
                    'city' => 'Rucavas nov.',
                    'country' => 'LV',
                    'postal_code' => 'LV-3477',
                    'phone' => '+374 374337352',
                    'fax' => '+374 37433752',
                    'email' => 'jj-work@mail.lv',
                    'homepage' => 'jj-work.lv',
                    'bank_name' => 'Luminor',
                    'bank_account_number' => 'LV52 4210 3623 1067 7644',
                    'status' => 'insolvency',
                    'note' => 'Sabiedriba ar ierobezotu atbildibu ',
                    'created_at' => '2016-02-08 12:30:11',
                    'updated_at' => '2020-04-05 10:11:19']);

                DB::table('debtors')->insert([
                    'company' => 'SIA KKK',
                    'created_by' => $id,
                    'reg_number' => '44103139989',
                    'debt' => '9900.00',
                    'legal_address' => 'Skukisi, "Rukisi"',
                    'city' => 'Garkalnes nov.',
                    'country' => 'LV',
                    'postal_code' => 'LV-2137',
                    'phone' => '+372 374637352',
                    'fax' => '+374 37463752',
                    'email' => 'siawork@mail.lv',
                    'homepage' => 'siakwork.lv',
                    'bank_name' => 'Swedbank',
                    'bank_account_number' => 'LV BANK 441031 39989',
                    'status' => 'hopeless',
                    'note' => 'Sabiedriba ar ierobezotu atbildibu ',
                    'created_at' => '2014-02-11 16:30:11',
                    'updated_at' => '2020-02-07 10:11:39']);

                DB::table('debtors')->insert([
                    'company' => 'GOD HAND',
                    'created_by' => $id,
                    'reg_number' => '43602026495',
                    'debt' => '5740.00',
                    'legal_address' => 'Edvarta Virzas iela 1',
                    'city' => 'Iecavas nov., Iecava ',
                    'country' => 'LV',
                    'postal_code' => 'LV-3913',
                    'phone' => '+371 36563752',
                    'fax' => '+371 36563752',
                    'email' => 'handgod@mail.lv',
                    'homepage' => 'hundod.lv',
                    'bank_name' => 'Swedbank',
                    'bank_account_number' => 'LV74 1243 6020 2649 8125',
                    'status' => 'hopeless',
                    'note' => '(IK)',
                    'created_at' => '2018-06-16 08:30:11',
                    'updated_at' => '2020-01-05 01:11:39']);

                DB::table('debtors')->insert([
                    'company' => '"Mix L" ',
                    'created_by' => $id,
                    'reg_number' => '45403031751',
                    'debt' => '2920.77',
                    'legal_address' => 'Dzeguzu iela 7 - 20',
                    'city' => 'Riga',
                    'country' => 'LV',
                    'postal_code' => 'LV-1007',
                    'phone' => '+371 22563731',
                    'fax' => '+371 22563731',
                    'email' => 'mixl@mail.lv',
                    'homepage' => 'seamixl.lv',
                    'bank_name' => 'Luminor',
                    'bank_account_number' => 'LV57 2345 4030 3453 1751',
                    'status' => 'hopeless',
                    'note' => '(SIA) ',
                    'created_at' => '2019-06-16 08:30:41',
                    'updated_at' => '2020-01-07 05:01:39']);
        }
    }
}


